language: node_js
node_js:
- '5.8.0'

sudo: false

cache:
  directories:
  - node_modules
  - bower_components

before_install: # Prep and logging
- npm config set spin false
- npm --version
- mkdir travis-phantomjs
- wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
- tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
- export PATH=$PWD/travis-phantomjs:$PATH
- phantomjs --version

install: # Install dependencies
- npm install -g bower
- npm install
- bower install

script: # run tests
- npm run test

# This is in script for 2 reasons:
# after_script doesn't fail the build
# deploy provider script doesn't give us the same context
after_success:
- >
  if [[ "master dev" =~ $TRAVIS_BRANCH ]] && [[ "false" == $TRAVIS_PULL_REQUEST ]]; then
    scripts/travis_deploy.sh
  fi
env:
  global:
  - DEPLOY_APP=madison-kerndt
